### ISSUE TITLE
bug - custom collections with grid cover+details view

### ISSUE THREAD

**Issue by kirbysblockball** [Darknior/RVGM-BT-Theme#25]
![IMG20210324130357](https://user-images.githubusercontent.com/69836769/112243438-a3c2ad80-8ca1-11eb-97cf-d5f390b0b62c.jpg)
i love this theme, but i'm having a problem - when using the "grid cover+details" view, the gray section on the right side of the screen is not big enough for the details. this only happens with custom collections

**Comment by Darknior** [comment]
Ok thanks for the feedback, i will see if i can found a solution. Because for me i don't know how is it possible to have a bug only on the Collection view. I think it's more an Emulation Station bug.

**Comment by Darknior** [comment]
Fixed from a long time
