### ISSUE TITLE
Ajout collection

### ISSUE THREAD

**Issue by flyingp1** [Darknior/RVGM-BT-Theme#27]
Bonjour,
En utilisant ton thème, j'ai crée une collection Beat'em All (Beat'em up). 
J'aimerai donc la partager pour qu'elle puisse être incorporé à ton thème pour en faire profiter le plus grand nombre.
Le descriptif est juste en français, il faudrait le traduire dans les autres langues.
[RVGM-BT-Theme.zip](https://github.com/Darknior/RVGM-BT-Theme/files/6457311/RVGM-BT-Theme.zip)

**Comment by Darknior** [comment]
Salut :)
Merci beaucoup pour ton initiative, c'est vraiment super sympa :)
Effectivement avec tout mon travail actuellement je n'ai pas eu el temps de faire bcp de mises a jour ... et fan de Beat'em ALL/UP moi aussi je te comprends ... je bosse sur un set de ouf pour OpenBOR, c'est pour te dire comme j'aime ca :)

Mais du coup, J'ai déjà utilisé les graphismes de Street of Rage pour le systeme openbor. Et j'ai me bien que le theme varie et change de jeu pour chaque systeme ou collection ... donc ce qui ferait sens si tu as envie de t'amuser et de m'aider serait de trouver une bonne idée avec un autre jeu, c'est pas les jeux de castagne qui manquent ...
Trouver des graphismes HD qui iraient avec et les proposer ici. Mais  il y a des règles dans mon theme qui le rende aussi "beau" selon mes gouts évidement ...

- Le background doit être HD, propre sans personnages, pas déformé, comme un decors de cinéma ou on va placer le sprite dedans.
- Le Sprite, ben comme tu as fais, bien découpé propre et qui s'intègre au décors.
- Enfin le titre, si tu as remarqué, je l'écris de la mm manière que le VRAI ti tre du jeu qui m'a inspiré, du coup c qd mm un taf graphique important et c'est pour ca que j'ai peu de collections, mais qd c fait ca claque bien :)

Pour en revenir a ton envois, le titre et écrit un peu comme un titre de vieux journal, c'est peut être pas bête d'utiliser cette idée, faire un fond en forme de journal de jeu vidéo avec des tas de crimes de partout ... et après on pourrait légèrement animes les vignettes du journal, un truc du genre ...

**Comment by flyingp1** [comment]
En effet c'est logique de ne pas utiliser plusieurs fois le même thème. Je vais voir si je trouve des images sympas et les proposer ici pour validation. 

Pour les typos ce n'est pas évident de trouver des polices de jeux vidéo mais je vais voir.
Juste une petite remarque en passant, sur la collection arcade, dans le descriptif en français, il y a une petite coquille, il est écrit "séléction" alors que c'est "sélection" ;)

**Comment by flyingp1** [comment]
Salut, je te propose pour le moment les personnages, le fond viendra en fonction du choix ;)
Il y a essentiellement du Final Fight car c'est sans doute avec Street of Rage le jeu le plus marquant du genre.
![Hugo 01](https://user-images.githubusercontent.com/84006913/117939030-f581ce80-b307-11eb-88c4-1cf3062756e6.png)


![Captain Commando 01](https://user-images.githubusercontent.com/84006913/117938423-5066f600-b307-11eb-90f6-6b68d1979d0f.png)
![Cody 01](https://user-images.githubusercontent.com/84006913/117938425-50ff8c80-b307-11eb-93df-03f07d7181f9.png)
![Cody 02](https://user-images.githubusercontent.com/84006913/117938429-5230b980-b307-11eb-8424-1567e40b63b3.png)
![Guy 01](https://user-images.githubusercontent.com/84006913/117938430-52c95000-b307-11eb-9037-29f49ea438f8.png)

**Comment by flyingp1** [comment]
Un dernier pour la route :)
![Maki 01](https://user-images.githubusercontent.com/84006913/117939583-7e990580-b308-11eb-9c25-3ebc3eb01772.jpg)

**Comment by Darknior** [comment]
il y a de bonnes idée, et effectivement FF est un bon choix il n'est pas utilisé :)
Mais pour moi le choix justement ne commence jamais pas le sprite, c le plus simple à trouver ou à faire, découper un sprite sous photoshop avec la plume c un jeu d'enfant j'ai fias un totu sur la chaine Youtube de RVM.
Par contre trouver un background vide du jeu, qui ferait l'affaire, ou un ou tu saura effacer les personnages qui sont trop présent, ou une création perso comme j'ai fias pour le C64 ... etc ... ça c'est le plus chaud :)
Le mieux c plutot de présenter un fond avec un sprite choisi positionné dessus rapido pour voir le rendu :)

**Comment by flyingp1** [comment]
Ok je pars sur Final Fight, reste à trouver un fond. J'ai des idées mais reste à trouver ça maintenant :)

**Comment by Darknior** [comment]
Plus de nouvelles depuis trop longtemps ...
