### ISSUE TITLE
Missing systems?

### ISSUE THREAD

**Issue by Tasosgemah** [Darknior/RVGM-BT-Theme#47]
I noticed there are a few systems that are missing or don't have any assets for.

Nintendo Famicom (famicom)
Nintendo Super Famicom (sfc)
NEC Turbografx-16 (tg16)
NEC Turbografx-CD (tg16cd)

I know these systems are just different region versions of existing systems. But there are enough regional exclusives to justify a separate list of games for each.

**Comment by Darknior** [comment]
Ok, no problem, there are already existing in the original systems. And it switch automatically with your system language.
But to make it fine for you, i have also split them now.

**Comment by Darknior** [comment]
Like it is not really interesting for me, i've used the same artworks. 
Only the "logo" and "photo" are different
