### ISSUE TITLE
Nice Theme - just some minor suggestion to support all system for Retro-Bliss project

### ISSUE THREAD

**Issue by virtual-man007** [Darknior/RVGM-BT-Theme#54]
If you need donation let me know :) 

Systems Support:
roms/snescd (I've adopted snes-msu1 but description box is empty)
roms/genesis (I've adopted snes-msu1 but description box is empty)
roms/pspminis
roms/psvita (it's missing some art/elements)
roms/teknoparrot (it's missing some art/elements)
roms/vpinball (it''s missing some art/elements)

Collection Support *must have priority:
*btmups
castlevania
doubledragon
*lightgun
mario
megaman
mortalkombat
*oldschool (vman specifical arcade collection)
*racing
sonic
streetfighter
*trackball
zelda

**Comment by Darknior** [comment]
Hi, thanks you for using my theme.
I have found your project over the net here : https://www.youtube.com/user/VirtualMan007/videos
If i understand fine you are using Retrobat to play games on Windows with my RVGM theme, ok.

- snes-msu1 is already include in my theme, for sure.
- I must made same for genesis.
- PSP Mini is not a real console, it is only a mini version, there are same games, i don't understand why you want it ?
- PSCita is not emulated on Batocera for now, i've don't made it, and i have read on official emulator site that really a few of games are working, it is not really interesting ... maybe in the future.
- Teknoparot is not emulated on Batocera only on Retrobat, yes for sure it miss some art
- VPinball is made if i remember fine ??

- I'm not really working on collections ... it is a lot of work for something i will not use :(

It is really fine to write me to give some donation, it will help the project for sure ...
Now i will must add all the news systems from Batocera v35
And finish some other not 100% complete
And add more animations to make the theme more sexy :)

I must open a Patreon to help the project ... maybe you can help with it, or with an Paypal gift.

**Comment by virtual-man007** [comment]
Trust me retrobat I need those systems as we are custom :) , just the systems is all I need complete. I look forward to your updates :) a worthy theme and I have a ton of other digital assets as needed to help.
Find me on discord and you can request money from my paypal https://www.paypal.com/paypalme/virtualman007

**Comment by virtual-man007** [comment]
I'll adopt changes myself, thank you for providing the _resources

**Comment by Darknior** [comment]
> I'll adopt changes myself, thank you for providing the _resources

Ok perfect, has you wish :)
I have share them to help people to help me too ... to make this theme better for every one.
Please, if you release some update, think to PUSH them here for every one.
I have already plan to modify a lot the theme to make it better with more options, if i don't have your updates and new systems, they will maybe not work with the next versions ... and you will can't use the theme update.

**Comment by virtual-man007** [comment]
Yes certainly will, adding additional assets, avatar with smoke-light like you did (model3) add's pizzaz... great theme man!

**Comment by virtual-man007** [comment]
WiP but I need to update your info tab about it but gives you an ideal - leveraging your work effeciently and retaining look and feel! https://cdn.discordapp.com/attachments/693931455159730206/992418934106095746/smoke_avatar.mp4

**Comment by virtual-man007** [comment]
I'm rather friendly you can add me on Discord VirtualMan#3334 - I have a ton of resource we can use to automate all this for ya :) in a flash.

**Comment by virtual-man007** [comment]
I hate to bother you, the info.psd you suply I can't seem to edit the top bar info layer? I use gimp, anyway you can add that layer as Txt vs. image... ( I really want to retain same style you have)
![image](https://user-images.githubusercontent.com/33401499/177057779-d5835609-31d7-4126-bcc7-a553a38adf91.png)

**Comment by virtual-man007** [comment]
Vpinball copmleted with floating elements :) , just need those info overlays lol :) - I'm really pondering on animating plain logos ... 
![image](https://user-images.githubusercontent.com/33401499/177059457-778e6b73-0df6-4838-a144-6f45bca9e8f7.png)

**Comment by virtual-man007** [comment]
Title Animation Properties (simple scale) adding more life :) https://cdn.discordapp.com/attachments/762810755640328212/993312566673674260/more_animations_properties_starting_to_have_more_life.mp4

**Comment by Darknior** [comment]
> Title Animation Properties (simple scale) adding more life - it's breathing! :) https://cdn.discordapp.com/attachments/762810755640328212/993312566673674260/more_animations_properties_starting_to_have_more_life.mp4

Yes it is a good idea, you can add it to the theme and push it on git

**Comment by Darknior** [comment]
> I hate to bother you, the info.psd you suply I can't seem to edit the top bar info layer? I use gimp, anyway you can add that layer as Txt vs. image... ( I really want to retain same style you have) - I just want to change 4 info tabs to support 4 systems..
> 
> PSP Playstation Portable Minis
> 
> PSVita Playstation Vita
> 
> Teknoparrot Arcade Game / Coin-OP
> 
> Visual Pinball Pinball Game Engine
> 
> ![image](https://user-images.githubusercontent.com/33401499/177057779-d5835609-31d7-4126-bcc7-a553a38adf91.png)

yes it's only works fine with Photoshop.
Push your new systems on the git, i will accept them and update the info title for you :)

**Comment by virtual-man007** [comment]
Will do, you should see pull request within the hour or so.  Appreciate your help on info additions.
