### ISSUE TITLE
Light Gun / Mouse Controller icon

### ISSUE THREAD

**Issue by gigovx** [Darknior/RVGM-BT-Theme#57]
Since connecting a Mayflash Bar in Mode 2 there is no light gun/mouse indicator, only a square box next to the controller indicators (top left)

**Comment by Darknior** [comment]
Hi, yes i know i must add the missing icons to the theme

**Comment by Darknior** [comment]
It is fixed for now
https://github.com/Darknior/RVGM-BT-Theme/commit/0c18a98dff8a20c6be00d65633e5b1d82940ec5c

**Comment by Darknior** [comment]
Done
