### ISSUE TITLE
Odyssey System Broken with latest v36 Beta

### ISSUE THREAD

**Issue by jerryblade** [Darknior/RVGM-BT-Theme#62]
It appears that the most recent 36 Beta change in the system name from odyssey2 to o2em has also broken that system for the RVGM-BT-Theme (https://github.com/batocera-linux/batocera.linux/commit/36fa3ba8f0479f0944468880b146688aadb5abd1)

**Comment by Darknior** [comment]
ok thanks it will be fixed in next push

**Comment by udance4ever** [comment]
has this already been pushed?  I installed the theme last night and my Odyssey2 is working in v36c

**Comment by Darknior** [comment]
I don' remember what i have pushed last time, you must verify on git history.
And i can't push news for the moment, so new version of them i'm working on is toooo different from the actual and not XML compatible. Sorry

**Comment by udance4ever** [comment]
@jerryblade have you updated your theme recently?  does Odyssey now work on your end?

I ask because it works over here in v36c so if it indeed now works for you, please consider closing this issue :)

**Comment by jerryblade** [comment]
Yes it is closed thanks!
